### ISSUE TITLE
frotz crashing

### ISSUE THREAD

**Issue by h2359** [ifrotz/iosfrotz#290] opened 2018-09-13 00:53 UTC
hi my name is Brennen Kinch and I am totally blind i use frotz on my iPhone with voiceover and I have been noticing that lately it keeps crashing when I start the app  I tried uninstalling and reinstalling the app and it works for a little bit and then it crashes again the next time I start the app I have an iPhone 6s running the latest most current version of iOS can you help me thanks

**Comment by spathiwa** [comment] 2018-09-13 01:14
Hi Brenne,

If you are crashing during launch it might be because of a corrupt auto-save game, and it is crashing trying to resume the game.  One thing you can try is using 3D touch on Frotz to launch it.  I think this works even with VoiceOver on.  Do a hard press of the Frotz icon, and choose "Show Story List" to launch Frotz to the story list instead of resuming the current game.   If Frotz no longer crashes, then you can restart the game you were playing by choosing the (i) "more info" page for the game and selecting "restart story".   Then you can manually restore your most recent manually saved game.  (Obviously, you would lose any progress in the game since that point).   Please let me know if this works for you, and what game/story you were playing when encountering this bug.

Thanks and good luck.
Craig

**Comment by h2359** [comment] 2018-09-13 01:26
OK awesome this look like it did work the game that I was playing is called in good company Hope that helps

**Comment by spathiwa** [comment] 2018-09-13 01:43
Great to hear.  Thanks.

**Comment by spathiwa** [comment] 2018-09-13 01:43
I'll leave this issue open so I can experiment with that game and try to reproduce the crash, but I may not get to it for a while.

**Comment by spathiwa** [comment] 2020-07-10 04:22
Closing this because there's not enough info to reproduce the crash.

**Closed by spathiwa** 2020-07-10 04:22 UTC
