### ISSUE TITLE
Upping the max font limit a little more

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ifrotz/iosfrotz#258] opened 2015-05-29 22:25 UTC
```
I know I've already requested that the max font size limit be upped, and that 
was very kindly accomodated.

At the time, I thought to myself "Hmmm, it could stand to be a little larger to 
be really comfortable on the eyes". I'm using Baskerville, which I think is by 
itself a smaller font. I then thought "Let's not look a gift horse in the 
mouth".

But my eyes have begged me to request another raise of the max font size limit, 
if that's ok. :) I don't think you have to worry about how big is too big - 
that's something for the player to worry about!
```

Original issue reported on code.google.com by `ilprimoc...@gmail.com` on 19 Apr 2015 at 10:52

**Comment by spathiwa** [comment] 2020-07-10 04:13
Duplicate of #299.
Bumping max font size to 32 on all devices.

**Closed by spathiwa** 2020-07-10 04:13 UTC
Labels: Priority-Medium, Type-Enhancment, auto-migrated, duplicate
