### ISSUE TITLE
Restart Story crashes Frotz

### ISSUE THREAD

**Issue by Vbarding** [ifrotz/iosfrotz#309] opened 2020-09-06 20:13 UTC
In the last week, anytime I try to restart a story with Frotz, it immediately crashes back to the home page.  This is on an iPad Pro (2018 version)

**Comment by spathiwa** [comment] 2020-09-06 21:23
This is in the recent 1.8.5 Frotz update?
I’m not able to reproduce. 
Is this just one specific story or any story?
Are you restarting using the restart command in the story or the button next to Resume on the story details page? 
If it’s one specific story, please let me know which one and if possible attach a saved game for the that story here.  Thanks.

**Comment by spathiwa** [comment] 2020-09-06 21:24
Never mind.  I did reproduce. Appears to be iPad only.  Thanks for the report.

**Comment by spathiwa** [comment] 2020-09-07 23:37
Fixed in 1.8.6.

**Closed by spathiwa** 2020-09-07 23:37 UTC
