### ISSUE TITLE
Text ending in [More] before splash screen is not displayed

### ISSUE THREAD

**Issue by pgerhardy** [ifrotz/iosfrotz#307] opened 2020-07-25 01:00 UTC
This issue was seen in Infocom's Trinity and Frotz 1.8.4. 

After entering the door at Long Water, the game is supposed to display a block of text ending in "[More]". After pressing a key, the game's title screen should then be displayed. Instead, after entering the door Frotz will jump directly to displaying the title screen.

**Comment by spathiwa** [comment] 2020-07-25 01:06
If you can, please attach a saved game where this can be reproduced, and the exact version of Trinity you are using (from the “version” command).  Thanks.

**Comment by pgerhardy** [comment] 2020-07-25 01:32
The version is: Release 12 / Serial Number 860926 (Interpreter 1 Version F).

I attached a save game file just at the point before entering the door, so "e" or "enter door" should trigger the bug.
[trinity_bug.zip](https://github.com/ifrotz/iosfrotz/files/4974745/trinity_bug.zip)

**Comment by spathiwa** [comment] 2020-07-25 07:27
So, this is really a bug in the Trinity game file itself; it assumes no screens are bigger than 80 columns by 40 rows, so tries to force a [More] prompt just by outputting 41 rows of text and then immediately clearing the screen and displaying the title screen, expecting the text output driver to automatically pause when it tries to output that much text.  It was written before the invention of scrolling views.
Window/Unix frotz and Gargoyle interpreters will also exhibit the same behavior if your window is sized to 42 rows or more.

That said, I can try to detect this behavior in iOS Frotz and special-case it.  
I have also been thinking of changing the way Frotz clears the screen and have it retain history before the screen clear; just scroll a large gap so it looks like the screen cleared, but you could still scroll back up.  That would help but it would still be weird in this case because the game displays the title screen in a fixed-width font by expanding the status line, so you'd have to skip past the title screen when it restores the status line to normal before you could scroll up.

**Comment by spathiwa** [comment] 2020-07-25 07:41
Oh, in case you didn't already figure it out by playing on another platform, the text you missed is:

>e
As you wade to the threshold a familiar roadrunner flutters past. The ruby
in its beak gleams enticingly as it slips through the white door.

All color abruptly drains from the landscape. Trees, sky and sun flatten
into a spherical shell, with you at the very center. A hissing in your ears
becomes a rumble, then a roar as the walls of the shell collapse inward,
faster and faster.

"This way, please."

You turn, but see no one.

"This way," the voice urges. "Be quick."

The space around you articulates. "No!" your mind shudders. "That's not a
direction!"

"It's a perfectly legitimate direction," retorts the voice with cold
amusement. "Now come along."

**Comment by pgerhardy** [comment] 2020-07-25 09:11
Thank you for this explanation, and thank you for Frotz which brings me much joy!

It must be a challenge to keep up with that kind of legacy hacks in the game files. Infocom had it easy, needing only to be compatible with themselves.

I guess the issue can be closed then.

**Comment by spathiwa** [comment] 2020-07-25 15:49
Thanks for the kind words. 

I’ll leave the issue open for a bit to track any sort of workaround I think of. 

Actually, Infocom had it pretty hard because there were so many more different platforms they had to run on with different quirks and tiny memory foot prints... everything from Atari 400 and TI 99/4a to Amiga.

**Comment by spathiwa** [comment] 2020-09-04 03:05
Fixed in 1.8.5.

**Closed by spathiwa** 2020-09-04 03:05 UTC
